### ISSUE TITLE
Not working in Windows 10

### ISSUE THREAD

**Issue by ion-storm** [jpann/ClickOnceCacheClear#2]
Nice app, first app i've seen that takes care of this issue, any chance on getting this working on Windows 10?  Specifically the app does not find any reg keys or folders.  The backup function however works.

**Comment by jpann** [comment]
I'll try to get some time to test it on Windows 10.

By default, the app only checks and removes certain [ClickOnce cache registry keys](https://github.com/jpann/ClickOnceCacheClear/blob/master/mClickOnceCacheClear/mClickOnceCacheClear/ClickOnceCache.cs#L28) as defined in the [app.config](https://github.com/jpann/ClickOnceCacheClear/blob/master/mClickOnceCacheClear/mClickOnceCacheClear/app.config#L15)'s SearchTerms setting. Unfortunately, I wrote this for a very specific ClickOnce application, so those are the only search terms included. You'd have to check out HKEY_CURRENT_USER\Software\Classes\Software\Microsoft\Windows\CurrentVersion\Deployment\SideBySide\2.0\ to find the appropriate terms for your application and set them in the app.config. For example, you may have issues with GitHub's Windows application and the ClickOnce cache, which is here HKEY_CURRENT_USER\Software\Classes\Software\Microsoft\Windows\CurrentVersion\Deployment\SideBySide\2.0\Components\github.exe_317444273a93ac29_0003.0002_none_a7f1ade3c3870c83, so you'd add 'github.exe_317444273a93ac29_0003.0002_none_a7f1ade3c3870c83' as a search term. Applications will likely have search different strings you'd have to use in your search terms. Hope that helps

**Comment by ion-storm** [comment]
Ah, thanks, yea I was testing with a different clickonce application called screenconnect, clearing the cache and reg keys manually resolved it.  Nice tool btw :)
